---
# tasks file for change_role_pg_master
  - block:

    - name: Stop service postgresql
      ansible.builtin.service:
        name: postgresql-15
        state: stopped

    - name: Remove data dir
      ansible.builtin.file:
        path: "/var/lib/pgsql/15/data"
        state: absent

    - name: Create data dir
      ansible.builtin.file:
        path: "/var/lib/pgsql/15/data"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Get backup DB without replication slot
      become_user: postgres
      ansible.builtin.shell: "pg_basebackup -R -h {{ hostvars[item].ansible_host }} -U {{ pg_replication_user }} -D /var/lib/pgsql/15/data"
      with_items: "{{ groups.standby }}"
      when: not use_replication_slot

    - name: Get backup DB with replication slot
      become_user: postgres
      ansible.builtin.shell: "pg_basebackup -R -h {{ hostvars[item].ansible_host }} -U {{ pg_replication_user }} -D /var/lib/pgsql/15/data -S {{ pg_replication_slot }}"
      with_items: "{{ groups.standby }}"
      when: use_replication_slot

    - name: Start service postgresql
      ansible.builtin.service:
        name: postgresql-15
        state: started

    become: yes
