db_servers:
  hosts:
    server01:
      ansible_host: 192.168.1.19
      ansible_user: "{{ server01_user }}"
      ansible_password: "{{ server01_pass }}"
    server02:
      ansible_host: 192.168.1.18
      ansible_user: "{{ server02_user }}"
      ansible_password: "{{ server02_pass }}"

master:
  hosts:
    server01:


standby:
  hosts:
    server02:
