db_servers:
  hosts:
    server01:
      ansible_ssh_host: 192.168.1.14
      ansible_ssh_port: 22
    server02:
      ansible_ssh_host: 192.168.1.15
      ansible_ssh_port: 22
  vars:
    ansible_connection: ssh
    ansible_user:       "root"
    ansible_ssh_pass:   "1q2w3e"   


master:
  hosts:
    server01:


standby:
  server02:
