db_servers:
  hosts:
    server01:
      ansible_host: 192.168.1.14
    server02:
      ansible_host: 192.168.1.15
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: 1q2w3e
    ansible_ssh_port: 22


master:
  hosts:
    server01:


standby:
  hosts:
    server02:
